### ISSUE TITLE
Undocumented opcode emulation (negate-with-carry)

### ISSUE THREAD

**Issue by gregdionne** [MiSTer-devel/AliceMC10_MiSTer#3]
Nice project!

Any plans on supporting some of the more esoteric quirks of the MC6801?

I use the undocumented negate-with-carry instructions (opcodes $42, $52, $62, $72) for multi-byte math and to negate the D register.  I believe these are equivalent to issuing a "subtract-with-carry" from zero.  The others I use from time-to-time are the sign-extend instructions ($02, $03) that affect the A register.  

I've been writing an opcode tester for the MC-10, with the hopes of updating the JavaScript emulator in a way that emulates the PEEKs and POKEs of youth... 

Best,
Greg Dionne

**Comment by pcornier** [comment]
The 6801 is coming from OpenCores (https://opencores.org/projects/mc6803). I understand that it can be very frustrating not having all these undocumented opcodes working. Unfortunately, I'm not going to modify the CPU as I'm not the original author but it's completely possible to replace it by a more accurate one if another one exists. I'd be happy to update the MC-10 core!

**Comment by gregdionne** [comment]
Thanks Pierre!

I've logged an enhancement.  Your project got some kudos on a Facebook group.  I hope to try it out soon.

Best,
-Greg
